server port: 8000
jwt secret key: "Xp2s5v8y/B?E(H+MbQeThVmYq3t6w9z$C&F)J@NcRfUjXnZr4u7x!A%D*G-KaPdS"
database host: "localhost"
database port: "5432"
database user: "CE_Backend"
database password: "0000"
database name: "Sharif_Stack_Exchange"
